server:
  port: ${server.port:7000}

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    config:
      topic:
        partitions: ${kafka.topic.default.partitions:3}
        replicas: ${kafka.topic.default.replicas:3}
        partitions-dlq: ${kafka.topic.default.partitions:3}
        replicas-dlq: ${kafka.topic.default.replicas:3}
      bootstrapServers: ${kafka.servers}
      producer:
        acks: all
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        retries: 10

app:
  producer:
    kafka:
      shell-command-topic-name: ${shell.command.queue.name}
